// Generated by setup.html on 2026-09-12T10:03:05.699Z
// This file holds YOUR project's key - keep it next to index.html.
window.SUPABASE_URL = "https://xmsimjbfuidjexbsiwxv.supabase.co";
window.SUPABASE_KEY = "sb_publishable_XSeAATHllBZWMr4N6aJNBA_tNNK0oZ1";
